Web.SBS/Models/DTO/UsuarioBusquedaDto.cs
using Newtonsoft.Json;

namespace Web.SBS.Models.DTO
{
    public class FiltroBusquedaUsuarioDto
    {
        public int RolId { get; set; }
        public string CodigoUsuario { get; set; }
    }
    public class BusquedaUsuarioDto
    {
        [JsonProperty(PropertyName = "UsuarioId")]
        public int UsuarioId { get; set; }
        [JsonProperty(PropertyName = "CodigoUsuario")]
        public string CodigoUsuario { get; set; }
        [JsonProperty(PropertyName = "PrimerNombre")]
        public string PrimerNombre { get; set; }
        [JsonProperty(PropertyName = "SegundoNombre")]
        public string SegundoNombre { get; set; }
        [JsonProperty(PropertyName = "ApellidoPaterno")]
        public string ApellidoPaterno { get; set; }
        [JsonProperty(PropertyName = "ApellidoMaterno")]
        public string ApellidoMaterno { get; set; }
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }
    }
}

Web.SBS/Models/ErrorViewModel.cs
using System;

namespace Web.SBS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web.SBS/Models/UsuarioModel.cs
using System.Collections.Generic;

namespace Web.SBS
{
    public class UsuarioModel
    {
        public int UsuarioId { get; set; }
        public int RolId { get; set; }
        public string CodigoUsuario { get; set; }
        public string ClaveSecreta { get; set; }
        public string Email { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Alias { get; set; }
        public int PrimeraVezLogin { get; set; }
        public int Activo { get; set; }
    }
}

Web.SBS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Web.SBS.Models;

namespace Web.SBS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web.SBS/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using Web.SBS.Models.DTO;
using Web.SBS.Providers.Interfaces;

namespace Web.SBS.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ILogger<Controller> _logger;
        private readonly IUsuarioProvider _usuarioProvider;

        /// <summary>
        /// UsuarioController
        /// </summary>
        /// <param name="logger"></param>
        /// <param name="usuarioService"></param>
        public UsuarioController
            (
            ILogger<Controller> logger,
            IUsuarioProvider usuarioProvider
            )
        {
            _logger = logger;
            _usuarioProvider = usuarioProvider;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// GrabarUsuario
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        [HttpPost("Grabar")]
        public JsonResult GrabarUsuario([FromBody] UsuarioModel param)
        {
            var success = true;
            int result = 0;

            try
            {
                result = _usuarioProvider.GrabarUsuario(param).Result;
            }
            catch (Exception ex)
            {
                success = false;
                _logger.LogError(default(EventId), ex, ex.Message);
            }

            return Json(new
            {
                success,
                data = result
            });
        }

        /// <summary>
        /// EliminarUsuario
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        [HttpPost("Eliminar")]
        public JsonResult EliminarUsuario([FromBody] int usuarioId)
        {
            var success = true;
            bool result = false;

            try
            {
                result = _usuarioProvider.EliminarUsuario(usuarioId).Result;
            }
            catch (Exception ex)
            {
                success = false;
                _logger.LogError(default(EventId), ex, ex.Message);
            }

            return Json(new
            {
                success,
                data = result
            });
        }

        /// <summary>
        /// BuscarUsuario
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        [HttpPost("Buscar")]
        public JsonResult BuscarUsuario([FromBody] FiltroBusquedaUsuarioDto param)
        {
            var success = true;
            IEnumerable<BusquedaUsuarioDto> lista = null;

            try
            {
                lista = _usuarioProvider.BuscarUsuario(param).Result;
            }
            catch (Exception ex)
            {
                success = false;
                _logger.LogError(default(EventId), ex, ex.Message);
            }

            return Json(new
            {
                success,
                data = lista
            });
        }

    }
}

Web.SBS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web.SBS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.SBS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web.SBS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web.SBS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web.SBS/Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Usuario";
}

<div class="text-center">
    <h1 class="display-4">Usuario</h1>
    <p>Usuario</p>
</div>

@section scripts{

    <script type="text/javascript">

        var urlBuscarUsuario = '@Url.Action("BuscarUsuario", "Usuario", new { area = "" })';
        var urlGrabarUsuario = '@Url.Action("GrabarUsuario", "Usuario", new { area = "" })';
        var urlEliminarUsuario = '@Url.Action("EliminarUsuario", "Usuario", new { area = "" })';

    </script>

    <script type="text/javascript" src="~/js/Usuario/Index.js"></script>
}